version: '3.8'
services:

  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: jason_flask
    environment:
      MONGODB_USERNAME: Your_Username
      MONGODB_PASSWORD: Your_Password
      MONGODB_HOSTNAME: jason_mongo
    # ports:
    #  - 8080:8080
    expose:
     - 8080

  mongodb:
    image: mongo:5.0
    container_name: jason_mongo
    expose:
     - 27017
    # ports:
    #   - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Your_Username
      - MONGO_INITDB_ROOT_PASSWORD=Your_Password


  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: jason_nginx
    ports:
     - "80:80"
     - "443:443"


# networks:
#   frontend:
#     driver: bridge
#   backend:
#     driver: bridge

# volumes:
#   mongodbdata:
#     driver: local
#  appdata:
#    driver: local
#  nginxdata:
#    driver: local

